### ISSUE TITLE
Remove UA targeting

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-useragent#24]
Use of this module for UA targeting of styles is somewhat problematic.  Product developers are required to label the page at runtime using the correct UA family and version classes.  It's hard to determine what those are, how to detect the UA, and adds unacceptable friction for product developers.

The primary use case for UA targeting is applying a special style in UA 1 that fixes a UA-specific bug, but which breaks other UAs.

Instead of the solution this module has been providing, we have decided to deal with the problem using these solutions in order of preference:

1. Compromise the design to avoid this situation
2. Use browser hacks so ensure that the style only targets that browser
3. Use JavaScript (only as last resort)

As a result, we should modify this module to remove the UA style targeting functionality.  Depdendent modules that are using this should be updated to use one of the methods above.

**Comment by AlbertoElias** [comment]
Not used anymore
