### ISSUE TITLE
Deprecate this module

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-useragent#26]
CSS:

* Add deprecation warning to ouseragenttarget and prefixer
* Remove remaining UA targeting from other modules (https://github.com/Financial-Times/o-useragent/issues/24)

JS:

* Replace any uses of useragent for prefixing in other modules with the canonical name and ensure that they are covered by the polyfill service (https://github.com/Financial-Times/polyfill-service/issues/178)
* Remove any public methods we've never used in other modules (see https://github.com/search?l=javascript&q=o-useragent&ref=searchresults&type=Code&utf8=%E2%9C%93)

Meta:

* Update module status to deprecated and release a minor version

**Comment by expe** [comment]
The support status has also been updated to deprecated #28
